# Generated by Django 5.1.4 on 2025-01-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(unique=True, upload_to='documents'),
        ),
    ]
