# Generated by Django 5.1.4 on 2025-01-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_document_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
