# Generated by Django 5.1.4 on 2025-01-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_document_docfile_document_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
